theme: jekyll-theme-cayman
title: OperonTop
description: Work for cause, not for applause. Live life to express, not to impress. Don't strive to make your presence noticed, just make your absence felt.
